version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "backend-500"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-a4kr4w7vumz7"
s3_prefix = "500-backend"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
